export const DIVVY_API = "https://api.divvy.bet/"
// "https://api.divvy.bet/"
// "http://localhost/"
export const DIVVY_API_GET_SPORTS = "sports"
export const DIVVY_API_GET_LIVE_MARKETS = "livemarkets"
export const DIVVY_API_GET_SEASONS = "seasons/"
export const DIVVY_API_GET_BETS = "bets/"
export const DIVVY_API_STORE_BETS = "add_bet"
export const DIVVY_API_STORE_TXNS = "send_txn"
export const DIVVY_API_GET_POOL = "pool/"
export const DIVVY_WEBSOCKET_API = "wss://api.divvy.bet/ws_txns"
export const DIVVY_API_GET_TRANS = "transactions"
export const DIVVY_API_SOLBUST = "/solbust/bet"
export const DIVVY_API_COMMENCED_MARKETS = "commenced_markets"
